// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coyzoyiwghpmdxqnmjro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNveXpveWl3Z2hwbWR4cW5tanJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjQ4MzEsImV4cCI6MjA3NDE0MDgzMX0.AabxamQ7x9nxz1cHpJVMqVAxK5FxzXx6v4cI5S1ruA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});